export const civsData = [
  "Armenians",
  "Aztecs",
  "Bengalis",
  "Berbers",
  "Bohemians",
  "Britons",
  "Bulgarians",
  "Burgundians",
  "Burmese",
  "Byzantines",
  "Celts",
  "Chinese",
  "Cumans",
  "Dravidians",
  "Ethiopians",
  "Franks",
  "Georgians",
  "Goths",
  "Gurjaras",
  "Huns",
  "Incas",
  "Hindustanis",
  "Italians",
  "Japanese",
  "Jurchens",
  "Khitans",
  "Khmer",
  "Koreans",
  "Lithuanians",
  "Magyars",
  "Malay",
  "Malians",
  "Mayans",
  "Mongols",
  "Persians",
  "Poles",
  "Portuguese",
  "Romans",
  "Saracens",
  "Shu",
  "Sicilians",
  "Slavs",
  "Spanish",
  "Tatars",
  "Teutons",
  "Turks",
  "Vietnamese",
  "Vikings",
  "Wei",
  "Wu",
  "Indians",
] as const;

export const civsAoeNetData = civsData;

export const civsEnrich = {
  Armenians: {
    goodMaps: ["Arena", "Fortress"],
    badMaps: ["Islands", "Nomad"],
    strongWith: "Infantería y Monjes",
  },
  Britons: {
    goodMaps: ["Arabia", "Cross"],
    badMaps: ["Islands", "Nomad"],
    strongWith: "Arqueros",
  },
  Franks: {
    goodMaps: ["Arabia", "Arena"],
    badMaps: ["Islands", "Nomad"],
    strongWith: "Caballería",
  },
  Vikings: {
    goodMaps: ["Islands", "Team Islands"],
    badMaps: ["Arabia", "Arena"],
    strongWith: "Naval e Infantería",
  },
  Mongols: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Arqueros a caballo",
  },
  Byzantines: {
    goodMaps: ["Arena", "Fortress"],
    badMaps: ["Arabia", "Nomad"],
    strongWith: "Defensa y Monjes",
  },
  Goths: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería",
  },
  Japanese: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería",
  },
  Chinese: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Arqueros",
  },
  Teutons: {
    goodMaps: ["Arena", "Fortress"],
    badMaps: ["Islands", "Nomad"],
    strongWith: "Infantería y Defensa",
  },
  Saracens: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Camellos y Comercio",
  },
  Turks: {
    goodMaps: ["Arena", "Fortress"],
    badMaps: ["Arabia", "Nomad"],
    strongWith: "Unidades de pólvora",
  },
  Persians: {
    goodMaps: ["Nomad", "Arabia"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Caballería y Elefantes",
  },
  Aztecs: {
    goodMaps: ["Arabia", "Arena"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Monjes",
  },
  Mayans: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Arqueros",
  },
  Huns: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Caballería",
  },
  Koreans: {
    goodMaps: ["Islands", "Team Islands"],
    badMaps: ["Arabia", "Nomad"],
    strongWith: "Torre y Naval",
  },
  Italians: {
    goodMaps: ["Islands", "Team Islands"],
    badMaps: ["Arabia", "Nomad"],
    strongWith: "Naval y Arqueros",
  },
  Slavs: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Asedio",
  },
  Magyars: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Caballería",
  },
  Incas: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Economía",
  },
  Indians: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Camellos y Economía",
  },
  Berbers: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Caballería y Naval",
  },
  Ethiopians: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Arqueros y Asedio",
  },
  Malians: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Economía",
  },
  Portuguese: {
    goodMaps: ["Islands", "Team Islands"],
    badMaps: ["Arabia", "Nomad"],
    strongWith: "Naval y Unidades de pólvora",
  },
  Burmese: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Monjes",
  },
  Khmer: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Elefantes y Economía",
  },
  Malay: {
    goodMaps: ["Islands", "Team Islands"],
    badMaps: ["Arabia", "Nomad"],
    strongWith: "Naval y Elefantes",
  },
  Vietnamese: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Arqueros y Exploración",
  },
  Bulgarians: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Asedio",
  },
  Cumans: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Caballería y Economía",
  },
  Lithuanians: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Caballería y Monjes",
  },
  Tatars: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Arqueros a caballo y Economía",
  },
  Burgundians: {
    goodMaps: ["Arabia", "Arena"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Caballería y Economía",
  },
  Sicilians: {
    goodMaps: ["Arena", "Fortress"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Defensa",
  },
  Bohemians: {
    goodMaps: ["Arena", "Fortress"],
    badMaps: ["Arabia", "Nomad"],
    strongWith: "Unidades de pólvora y Monjes",
  },
  Poles: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Caballería y Economía",
  },
  Hindustanis: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Arena", "Fortress"],
    strongWith: "Camellos y Economía",
  },
  Bengalis: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Elefantes y Monjes",
  },
  Dravidians: {
    goodMaps: ["Islands", "Team Islands"],
    badMaps: ["Arabia", "Nomad"],
    strongWith: "Naval e Infantería",
  },
  Gurjaras: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Camellos y Economía",
  },
  Romans: {
    goodMaps: ["Arena", "Fortress"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Defensa",
  },
  Georgians: {
    goodMaps: ["Arena", "Fortress"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Monjes",
  },
  Shu: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Infantería y Arqueros",
  },
  Wei: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Caballería y Arqueros",
  },
  Wu: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Naval y Arqueros",
  },
  Jurchens: {
    goodMaps: ["Arabia", "Nomad"],
    badMaps: ["Islands", "Team Islands"],
    strongWith: "Caballería y Arqueros",
  },
  Spanish: {
    goodMaps: ["Arena", "Nomad"],
    badMaps: ["Arabia", "Cross"],
    strongWith: "Unidades de pólvora y Comercio",
  },
};

// each image are in /public/civilizations/de/
export const civIconListData: Record<string, string> = {
  Armenians: "/civilizations/de/armenians.png",
  Aztecs: "civilizations/de/aztecs.png",
  Bengalis: "civilizations/de/bengalis.png",
  Berbers: "civilizations/de/berber.png",
  Bohemians: "civilizations/de/bohemians.png",
  Britons: "civilizations/de/britons.png",
  Bulgarians: "civilizations/de/bulgarians.png",
  Burgundians: "civilizations/de/burgundians.png",
  Burmese: "civilizations/de/burmese.png",
  Byzantines: "civilizations/de/byzantines.png",
  Celts: "civilizations/de/celts.png",
  Chinese: "civilizations/de/chinese.png",
  Cumans: "civilizations/de/cumans.png",
  Dravidians: "civilizations/de/dravidians.png",
  Ethiopians: "civilizations/de/ethiopians.png",
  Franks: "civilizations/de/franks.png",
  Georgians: "civilizations/de/georgians.png",
  Goths: "civilizations/de/goths.png",
  Gurjaras: "civilizations/de/gurjaras.png",
  Huns: "civilizations/de/huns.png",
  Incas: "civilizations/de/inca.png",
  Hindustanis: "civilizations/de/hindustanis.png",
  Italians: "civilizations/de/italians.png",
  Japanese: "civilizations/de/japanese.png",
  Jurchens: "civilizations/de/jurchens.png",
  Khitans: "civilizations/de/khitans.png",
  Khmer: "civilizations/de/khmer.png",
  Koreans: "civilizations/de/koreans.png",
  Lithuanians: "civilizations/de/lithuanians.png",
  Magyars: "civilizations/de/magyars.png",
  Malay: "civilizations/de/malay.png",
  Malians: "civilizations/de/malians.png",
  Mayans: "civilizations/de/mayans.png",
  Mongols: "civilizations/de/mongols.png",
  Persians: "civilizations/de/persians.png",
  Poles: "civilizations/de/poles.png",
  Portuguese: "civilizations/de/portuguese.png",
  Romans: "civilizations/de/romans.png",
  Saracens: "civilizations/de/saracens.png",
  Shu: "civilizations/de/shu.png",
  Sicilians: "civilizations/de/sicilians.png",
  Slavs: "civilizations/de/slavs.png",
  Spanish: "civilizations/de/spanish.png",
  Tatars: "civilizations/de/tatars.png",
  Teutons: "civilizations/de/teutons.png",
  Turks: "civilizations/de/turks.png",
  Vietnamese: "civilizations/de/vietnamese.png",
  Vikings: "civilizations/de/vikings.png",
  Wei: "civilizations/de/wei.png",
  Wu: "civilizations/de/wu.png",
  Indians: "civilizations/de/indians.png",
};

export const civEnumListData: Record<string, string> = {
  armenians: "Armenians",
  aztecs: "Aztecs",
  bengalis: "Bengalis",
  berbers: "Berbers",
  bohemians: "Bohemians",
  britons: "Britons",
  bulgarians: "Bulgarians",
  burgundians: "Burgundians",
  burmese: "Burmese",
  byzantines: "Byzantines",
  celts: "Celts",
  chinese: "Chinese",
  cumans: "Cumans",
  dravidians: "Dravidians",
  ethiopians: "Ethiopians",
  franks: "Franks",
  georgians: "Georgians",
  goths: "Goths",
  gurjaras: "Gurjaras",
  huns: "Huns",
  incas: "Incas",
  hindustanis: "Hindustanis",
  italians: "Italians",
  japanese: "Japanese",
  jurchens: "Jurchens",
  khitans: "Khitans",
  khmer: "Khmer",
  koreans: "Koreans",
  lithuanians: "Lithuanians",
  magyars: "Magyars",
  malay: "Malay",
  malians: "Malians",
  mayans: "Mayans",
  mongols: "Mongols",
  persians: "Persians",
  poles: "Poles",
  portuguese: "Portuguese",
  romans: "Romans",
  saracens: "Saracens",
  shu: "Shu",
  sicilians: "Sicilians",
  slavs: "Slavs",
  spanish: "Spanish",
  tatars: "Tatars",
  teutons: "Teutons",
  turks: "Turks",
  vietnamese: "Vietnamese",
  vikings: "Vikings",
  wei: "Wei",
  wu: "Wu",
  indians: "Indians",
};

export const civAbbrEnumListData: Record<string, string> = {
  arm: "Armenians",
  azt: "Aztecs",
  ben: "Bengalis",
  ber: "Berbers",
  boh: "Bohemians",
  bri: "Britons",
  bul: "Bulgarians",
  brg: "Burgundians",
  bur: "Burmese",
  byz: "Byzantines",
  cel: "Celts",
  chi: "Chinese",
  cum: "Cumans",
  dra: "Dravidians",
  eth: "Ethiopians",
  fra: "Franks",
  geo: "Georgians",
  got: "Goths",
  gur: "Gurjaras",
  hun: "Huns",
  inc: "Incas",
  hin: "Hindustanis",
  ita: "Italians",
  jap: "Japanese",
  jur: "Jurchens",
  khi: "Khitans",
  khm: "Khmer",
  kor: "Koreans",
  lit: "Lithuanians",
  mag: "Magyars",
  mly: "Malay",
  mal: "Malians",
  may: "Mayans",
  mon: "Mongols",
  per: "Persians",
  pol: "Poles",
  por: "Portuguese",
  rom: "Romans",
  sar: "Saracens",
  shu: "Shu",
  sic: "Sicilians",
  sla: "Slavs",
  spa: "Spanish",
  tat: "Tatars",
  teu: "Teutons",
  tur: "Turks",
  vie: "Vietnamese",
  vik: "Vikings",
  wei: "Wei",
  wu: "Wu",
};
