import { unitLineIds } from "./units-ids";

export const unitLines: unitLinesType = {
  Ghulam: {
    units: ["Ghulam", "EliteGhulam"],
    unique: true,
    counteredBy: [],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Conscription",
      "Kasbah",
      "Stronghold-Infantry",
    ],
  },
  ShrivamshaRider: {
    units: ["ShrivamshaRider", "EliteShrivamshaRider"],
    unique: true,
    counteredBy: [],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Heresy",
      "Conscription",
      "Kshatriyas",
    ],
  },
  ChakramThrower: {
    units: ["ChakramThrower", "EliteChakramThrower"],
    unique: true,
    counteredBy: [],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      // 'Tracking',
      "Heresy",
      "Conscription",
      "Kasbah",
      "Kshatriyas",
      "Stronghold-Infantry",
    ],
  },
  Thirisadai: {
    units: ["Thirisadai"],
    unique: true,
    counteredBy: [],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "Ballistics",
      "Careening",
      "DryDock",
      "Devotion",
      "Faith",
      "Shipwright",
    ],
  },
  UrumiSwordsman: {
    units: ["UrumiSwordsman", "EliteUrumiSwordsman"],
    unique: true,
    counteredBy: [],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "WootzSteel",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Conscription",
      "Kasbah",
      "Stronghold-Infantry",
    ],
  },
  ArmoredElephant: {
    units: ["ArmoredElephant", "SiegeElephant"],
    counteredBy: [],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "SiegeEngineers-20",
      "WootzSteel",
      "Paiks",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy-Gurjaras",
      "Kshatriyas",
      "MedicalCorps",
    ],
  },
  Ratha: {
    units: ["Ratha", "EliteRatha"],
    unique: true,
    counteredBy: [],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ParthianTactics",
      "Paiks",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Conscription",
      "Kasbah",
    ],
  },

  Obuch: {
    units: ["Obuch", "EliteObuch"],
    unique: true,
    counteredBy: ["Samurai", "HandCannoneer"],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  HussiteWagon: {
    units: ["HussiteWagon", "EliteHussiteWagon"],
    unique: true,
    counteredBy: ["Mangonel", "BombardCannon"],
    upgrades: [
      "SiegeEngineers-20-1",
      "WagenburgTactics",
      "Devotion",
      "Faith",
      "Heresy",
    ],
  },
  Coustillier: {
    units: ["Coustillier", "EliteCoustillier"],
    unique: true,
    counteredBy: [
      "Spearman",
      "Boyar",
      "Kamayuk",
      "GenoeseCrossbowman",
      "Mameluke",
      "CamelRider",
      "WarElephant",
      "Knight",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Conscription",
    ],
  },
  Serjeant: {
    units: ["Serjeant", "EliteSerjeant"],
    unique: true,
    counteredBy: [
      "HandCannoneer",
      "Scorpion",
      "Conquistador",
      "Janissary",
      "OrganGun",
      "TeutonicKnight",
      "Samurai",
      "Slinger",
      "Cataphract",
      "JaguarWarrior",
      "Leitis",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      "Devotion",
      "Faith",
      "Heresy",
      // 'Tracking',
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  FlemishMilitia: {
    units: ["FlemishMilitia"],
    unique: true,
    counteredBy: [
      "HandCannoneer",
      "Scorpion",
      "Janissary",
      "OrganGun",
      "TeutonicKnight",
      "Samurai",
      "ChuKoNu",
      "PlumedArcher",
      "Slinger",
      "Cataphract",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      "Devotion",
      "Faith",
      "Stronghold-Infantry",
    ],
  },
  TradeCart: {
    units: ["TradeCart"],
    upgrades: [
      "GrandTrunkRoad",
      "Caravan",
      "Devotion",
      "Faith",
      "Heresy",
      "SilkRoad",
    ],
  },
  TradeCog: {
    units: ["TradeCog"],
    upgrades: [
      "GrandTrunkRoad",
      "Careening",
      "Carrack",
      "DryDock",
      "Caravan",
      "Devotion",
      "Faith",
      "Heresy",
      "Shipwright",
      "SilkRoad",
    ],
  },
  FishingShip: {
    units: ["FishingShip"],
    upgrades: [
      "Gillnets",
      "Careening",
      "Carrack",
      "DryDock",
      "Devotion",
      "Faith",
      "Heresy",
      "Shipwright",
    ],
  },
  TransportShip: {
    units: ["TransportShip"],
    upgrades: [
      "Careening-5",
      "Carrack",
      "DryDock-10",
      "Devotion",
      "Faith",
      "Heresy",
      "Shipwright",
    ],
  },
  Villager: {
    units: ["Villager"],
    upgrades: [
      "Wheelbarrow",
      "HandCart",
      "HeavyPlow",
      "DoubleBitAxe",
      "BowSaw",
      "TwoManSaw",
      "StoneMining",
      "StoneShaftMining",
      "GoldMining",
      "GoldShaftMining",
      "GrandTrunkRoad-GatheringSpeed",
      "Loom",
      "Sappers",
      "Forging-Villager",
      "IronCasting-Villager",
      "BlastFurnace-Villager",
      "ScaleMailArmor-Villager",
      "ChainMailArmor-Villager",
      "PlateMailArmor-Villager",
      "Supremacy",
      "Devotion",
      "Faith",
      "Heresy",
      "TreadmillCrane",
      "FlemishRevolution",
      "BurgundianVineyards",
      "Mahayana",
      "PaperMoney",
    ],
  },
  Missionary: {
    units: ["Missionary"],
    unique: true,
    counteredBy: [
      "EagleScout",
      "Spearman",
      "FlemishMilitia",
      "Archer",
      "Monk",
      "CamelRider",
      "ScoutCavalry",
      "ShotelWarrior",
      "GenoeseCrossbowman",
      "Arambai",
    ],
    upgrades: [
      "Sanctity",
      "Bloodlines",
      "BlockPrinting",
      "Fervor",
      "Husbandry",
      "Redemption",
      "Atonement",
      "Illumination",
      "Theocracy",
      "Inquisition",
      "Inquisition-1",
      "Devotion",
      "Faith",
      "Heresy",
    ],
  },
  Monk: {
    units: ["Monk"],
    counteredBy: [
      "Monk",
      "ScoutCavalry",
      "ShotelWarrior",
      "EagleScout",
      "Arambai",
    ],
    upgrades: [
      "Sanctity",
      "Sanctity-5",
      "Redemption",
      "Redemption-5",
      "Atonement",
      "Atonement-5",
      "HerbalMedicine-5",
      "Heresy",
      "Heresy-5",
      "Fervor",
      "Fervor-5",
      "Devotion",
      "Devotion-5",
      "Faith",
      "Faith-5",
      "Illumination",
      "Illumination-5",
      "BlockPrinting",
      "BlockPrinting-5",
      "Theocracy",
      "Theocracy-5",
      "Inquisition",
      "HussiteReforms",
      "Mahayana",
      "Bimaristan",
      "FirstCrusade",
    ],
  },
  DemolitionRaft: {
    units: ["DemolitionRaft", "DemolitionShip", "HeavyDemolitionShip"],
    counteredBy: ["Archer", "Mangonel"],
    upgrades: [
      "CilicianFleet-BlastRadius",
      "Careening",
      "Carrack",
      "DryDock",
      "Devotion",
      "Faith",
      "Heresy",
      "Shipwright",
    ],
  },
  FireGalley: {
    units: ["FireGalley", "FireShip", "FastFireShip"],
    counteredBy: [
      "DemolitionRaft",
      "TurtleShip",
      "BombardCannon",
      "Mangonel",
      "Scorpion",
      "BallistaElephant",
    ],
    upgrades: [
      "GreekFire",
      "Careening",
      "Carrack",
      "DryDock",
      "Devotion",
      "Faith",
      "Heresy",
      "Shipwright",
    ],
  },
  Galley: {
    units: ["Galley", "WarGalley", "Galleon"],
    counteredBy: [
      "FireGalley",
      "Mangonel",
      "BombardCannon",
      "BallistaElephant",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "CilicianFleet-Range",
      "Ballistas",
      "Chemistry",
      "Ballistics",
      "Careening",
      "Carrack",
      "DryDock",
      "Devotion",
      "Faith",
      "Heresy",
      "Shipwright",
    ],
  },
  CannonGalleon: {
    units: ["CannonGalleon", "EliteCannonGalleon"],
    counteredBy: [
      "Galley",
      "FireGalley",
      "DemolitionRaft",
      "Longboat",
      "Caravel",
      "Monk",
      "BombardCannon",
    ],
    upgrades: [
      "Artillery",
      "Arquebus",
      "Careening",
      "Carrack",
      "DryDock",
      "Devotion",
      "Faith",
      "Heresy",
      "Shipwright",
      "WagenburgTactics",
    ],
  },
  Arambai: {
    units: ["Arambai", "EliteArambai"],
    unique: true,
    civ: "Burmese",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Skirmisher",
      "CamelRider",
      "CavalryArcher",
      "Kamayuk",
      "Huskarl",
      "GenoeseCrossbowman",
      "Mameluke",
    ],
    upgrades: [
      "Bloodlines",
      "Ballistics",
      "PaddedArcherArmor",
      "ParthianTactics",
      "Husbandry",
      "Devotion",
      "Faith",
      "Conscription",
    ],
  },
  OrganGun: {
    units: ["OrganGun", "EliteOrganGun"],
    unique: true,
    civ: "Portuguese",
    counteredBy: [
      "Knight",
      "CamelRider",
      "ScoutCavalry",
      "Mangonel",
      "BombardCannon",
      "Condottiero",
      "Huskarl",
      "Longbowman",
      "Tarkan",
      "Konnik",
      "Boyar",
      "MagyarHuszar",
      "Coustillier",
      "Mameluke",
      "Cataphract",
      "SteppeLancer",
      "Mangudai",
    ],
    upgrades: [
      "SiegeEngineers-20-1",
      "Arquebus",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  Caravel: {
    units: ["Caravel", "EliteCaravel"],
    unique: true,
    civ: "Portuguese",
    counteredBy: [
      "FireGalley",
      "Longboat",
      "TurtleShip",
      "Mangonel",
      "BombardCannon",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "Ballistics",
      "Careening",
      "Carrack",
      "DryDock",
      "Devotion",
      "Faith",
      "Heresy",
    ],
  },
  SiegeTower: {
    units: ["SiegeTower"],
    counteredBy: [
      "ScoutCavalry",
      "Knight",
      "CamelRider",
      "SteppeLancer",
      "EagleScout",
      "ShotelWarrior",
      "Condottiero",
      "Tarkan",
      "Konnik",
      "Boyar",
      "MagyarHuszar",
      "Coustillier",
      "Mameluke",
      "Cataphract",
      "SteppeLancer",
    ],
    upgrades: [
      "FurorCeltica",
      "Ironclad",
      "Drill",
      "Devotion",
      "Faith",
      "Heresy",
    ],
  },
  Conquistador: {
    units: ["Conquistador", "EliteConquistador"],
    unique: true,
    civ: "Spanish",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Skirmisher",
      "CamelRider",
      "Mangonel",
      "Condottiero",
      "Huskarl",
      "Berserk",
      "Kamayuk",
      "EagleScout",
      "GenoeseCrossbowman",
      "Mameluke",
    ],
    upgrades: [
      "Bloodlines",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  TurtleShip: {
    units: ["TurtleShip", "EliteTurtleShip"],
    unique: true,
    civ: "Koreans",
    counteredBy: ["Monk", "BombardCannon", "Trebuchet", "Missionary"],
    upgrades: [
      "Ballistics",
      "SiegeEngineers-0-1",
      "Careening",
      "DryDock",
      "Devotion",
      "Faith",
      "Shipwright",
    ],
  },
  Longboat: {
    units: ["Longboat", "EliteLongboat"],
    unique: true,
    civ: "Vikings",
    counteredBy: ["FireGalley", "TurtleShip", "Mangonel", "BombardCannon"],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "Ballistics",
      "Careening",
      "DryDock",
      "Devotion",
      "Faith",
      "Heresy",
      "Bogsveigar",
    ],
  },
  Janissary: {
    units: ["Janissary", "EliteJanissary"],
    unique: true,
    civ: "Turks",
    counteredBy: [
      "Archer",
      "Skirmisher",
      "Mangonel",
      "BombardCannon",
      "Scorpion",
      "Condottiero",
      "Huskarl",
    ],
    upgrades: [
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  BallistaElephant: {
    units: ["BallistaElephant", "EliteBallistaElephant"],
    unique: true,
    civ: "Khmer",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "CamelRider",
      "Mangonel",
      "BombardCannon",
      "BatteringRam",
      "Scorpion",
      "Samurai",
      "EagleScout",
      "Kamayuk",
      "Huskarl",
      "Mameluke",
      "MagyarHuszar",
      "Coustillier",
      "Mangudai",
    ],
    upgrades: [
      "Bloodlines",
      "SiegeEngineers-20-1",
      "Ballistics",
      "Chemistry",
      "DoubleCrossbow",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Conscription",
    ],
  },
  FlamingCamel: {
    units: ["FlamingCamel"],
    unique: true,
    counteredBy: ["Spearman", "FlemishMilitia", "Archer", "Monk", "Scorpion"],
    upgrades: ["SiegeEngineers-20", "Conscription", "Bloodlines", "Husbandry"],
  },
  Petard: {
    units: ["Petard"],
    counteredBy: [
      "Archer",
      "CavalryArcher",
      "Scorpion",
      "EagleScout",
      "MagyarHuszar",
      "Coustillier",
      "Mangudai",
    ],
    upgrades: [
      "SiegeEngineers-40",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Kshatriyas",
    ],
  },
  Trebuchet: {
    units: ["Trebuchet"],
    counteredBy: [
      "ScoutCavalry",
      "Knight",
      "CamelRider",
      "Mangonel",
      "BombardCannon",
      "Trebuchet",
      "Petard",
      "BatteringRam",
      "EagleScout",
      "WoadRaider",
      "ThrowingAxeman",
      "Tarkan",
      "Konnik",
      "Boyar",
      "MagyarHuszar",
      "Coustillier",
      "Mameluke",
      "Cataphract",
      "SteppeLancer",
      "WarElephant",
      "BattleElephant",
    ],
    upgrades: [
      "Counterweights",
      "SiegeEngineers-20-1",
      "Chemistry",
      "Warwolf",
      "TimuridSiegecraft",
      "Kataparuto",
      "Ironclad",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  BombardCannon: {
    units: ["BombardCannon", "Houfnice"],
    counteredBy: [
      "ScoutCavalry",
      "Knight",
      "CamelRider",
      "BombardCannon",
      "Petard",
      "EagleScout",
      "Huskarl",
      "Cataphract",
      "WoadRaider",
      "ShotelWarrior",
      "Tarkan",
      "Konnik",
      "Boyar",
      "MagyarHuszar",
      "Coustillier",
      "Mameluke",
      "Cataphract",
      "SteppeLancer",
    ],
    upgrades: [
      "SiegeEngineers-20-1",
      "TorsionEngines",
      "Artillery",
      "Arquebus",
      "Ironclad",
      "Devotion",
      "Faith",
      "Heresy",
      "WagenburgTactics",
    ],
  },
  Mangonel: {
    units: ["Mangonel", "Onager", "SiegeOnager"],
    counteredBy: [
      "Monk",
      "ScoutCavalry",
      "Knight",
      "CamelRider",
      "Mangonel",
      "BombardCannon",
      "Petard",
      "ShotelWarrior",
      "WoadRaider",
      "Condottiero",
      "Huskarl",
      "EagleScout",
      "Longbowman",
      "Tarkan",
      "Cataphract",
      "MagyarHuszar",
      "Coustillier",
      "SteppeLancer",
      "Mangudai",
    ],
    upgrades: [
      "FurorCeltica",
      "Counterweights",
      "SiegeEngineers-20-1",
      "Chemistry",
      "TorsionEngines",
      "Shinkichon",
      "Ironclad",
      "Drill",
      "Devotion",
      "Faith",
      "Heresy",
    ],
  },
  BatteringRam: {
    units: ["BatteringRam", "CappedRam", "SiegeRam"],
    counteredBy: [
      "Militia",
      "ScoutCavalry",
      "Knight",
      "CamelRider",
      "Mangonel",
      "BombardCannon",
      "Petard",
      "KarambitWarrior",
      "Gbeto",
      "ShotelWarrior",
      "Condottiero",
      "EagleScout",
      "Conquistador",
      "WoadRaider",
      "ThrowingAxeman",
      "ChuKoNu",
      "Tarkan",
      "Mangudai",
      "Cataphract",
      "MagyarHuszar",
      "Coustillier",
    ],
    upgrades: [
      "FurorCeltica",
      "SiegeEngineers-20",
      "Ironclad",
      "Drill",
      "Devotion",
      "Faith",
      "Heresy",
      "TorsionEngines",
    ],
  },
  Scorpion: {
    units: ["Scorpion", "HeavyScorpion"],
    counteredBy: [
      "ScoutCavalry",
      "Knight",
      "CamelRider",
      "Mangonel",
      "BombardCannon",
      "Petard",
      "ShotelWarrior",
      "EagleScout",
      "Condottiero",
      "WoadRaider",
      "Tarkan",
    ],
    upgrades: [
      "FurorCeltica",
      "SiegeEngineers-20-1",
      "Ballistics",
      "Chemistry",
      "Rocketry-4",
      "TorsionEngines",
      "DoubleCrossbow",
      "Ballistas",
      "Ironclad",
      "Drill",
      "Devotion",
      "Faith",
      "Heresy",
    ],
  },
  HandCannoneer: {
    units: ["HandCannoneer"],
    counteredBy: [
      "Skirmisher",
      "CavalryArcher",
      "Mangonel",
      "Scorpion",
      "Condottiero",
      "RattanArcher",
      "PlumedArcher",
    ],
    upgrades: [
      "Shatagni",
      "Arquebus",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "WagenburgTactics",
    ],
  },
  KarambitWarrior: {
    units: ["KarambitWarrior", "EliteKarambitWarrior"],
    unique: true,
    civ: "Malay",
    counteredBy: [
      "Militia",
      "HandCannoneer",
      "Archer",
      "Knight",
      "JaguarWarrior",
      "TeutonicKnight",
      "Berserk",
      "Samurai",
      "Janissary",
      "OrganGun",
      "Slinger",
      "WarElephant",
      "Cataphract",
      "Boyar",
      "Conquistador",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  Gbeto: {
    units: ["Gbeto", "EliteGbeto"],
    unique: true,
    civ: "Malians",
    counteredBy: [
      "HandCannoneer",
      "Archer",
      "Monk",
      "Missionary",
      "Knight",
      "Mangonel",
      "Scorpion",
      "Samurai",
      "JaguarWarrior",
      "PlumedArcher",
      "Slinger",
      "Janissary",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  ShotelWarrior: {
    units: ["ShotelWarrior", "EliteShotelWarrior"],
    unique: true,
    civ: "Ethiopians",
    counteredBy: [
      "Militia",
      "HandCannoneer",
      "Knight",
      "CavalryArcher",
      "Mangonel",
      "Huskarl",
      "TeutonicKnight",
      "Janissary",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "RoyalHeirs",
      "Stronghold-Infantry",
    ],
  },
  Condottiero: {
    units: ["Condottiero"],
    unique: true,
    counteredBy: [
      "Archer",
      "Scorpion",
      "Samurai",
      "TeutonicKnight",
      "Cataphract",
      "Boyar",
    ],
    upgrades: [
      "Fereters-HP",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "GarlandWars",
      "WootzSteel",
      "Druzhina",
      "Chieftains",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Pavise",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Perfusion",
      "Stronghold-Infantry",
    ],
  },
  JaguarWarrior: {
    units: ["JaguarWarrior", "EliteJaguarWarrior"],
    unique: true,
    civ: "Aztecs",
    counteredBy: [
      "HandCannoneer",
      "Archer",
      "Knight",
      "Mangonel",
      "Scorpion",
      "Gbeto",
      "Slinger",
      "Janissary",
      "OrganGun",
      "Cataphract",
      "Boyar",
      "Conquistador",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "GarlandWars",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  Berserk: {
    units: ["Berserk", "EliteBerserk"],
    unique: true,
    civ: "Vikings",
    counteredBy: [
      "HandCannoneer",
      "JaguarWarrior",
      "TeutonicKnight",
      "PlumedArcher",
      "Slinger",
      "Janissary",
      "OrganGun",
      "Boyar",
      "Conquistador",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "Chieftains",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  TeutonicKnight: {
    units: ["TeutonicKnight", "EliteTeutonicKnight"],
    unique: true,
    civ: "Teutons",
    counteredBy: [
      "HandCannoneer",
      "Archer",
      "Monk",
      "Missionary",
      "Mangonel",
      "Scorpion",
      "Samurai",
      "Slinger",
      "ChuKoNu",
      "RattanArcher",
      "Janissary",
      "OrganGun",
      "Conquistador",
      "Leitis",
      "Obuch",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  Samurai: {
    units: ["Samurai", "EliteSamurai"],
    unique: true,
    civ: "Japanese",
    counteredBy: ["HandCannoneer", "Archer", "Knight"],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  Huskarl: {
    units: ["Huskarl", "EliteHuskarl"],
    unique: true,
    civ: "Goths",
    counteredBy: [
      "Mangonel",
      "WoadRaider",
      "Militia",
      "Samurai",
      "TeutonicKnight",
      "ThrowingAxeman",
      "Cataphract",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleMailArmor",
      "ChainMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Conscription",
      "Perfusion",
      "Anarchy",
      "Stronghold-Infantry",
    ],
  },
  ThrowingAxeman: {
    units: ["ThrowingAxeman", "EliteThrowingAxeman"],
    unique: true,
    civ: "Franks",
    counteredBy: [
      "HandCannoneer",
      "Archer",
      "JaguarWarrior",
      "TeutonicKnight",
      "Berserk",
      "Samurai",
      "Slinger",
      "Janissary",
      "OrganGun",
      "Conquistador",
      "Cataphract",
      "Boyar",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "BeardedAxe",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  WoadRaider: {
    units: ["WoadRaider", "EliteWoadRaider"],
    unique: true,
    civ: "Celts",
    counteredBy: [
      "Archer",
      "HandCannoneer",
      "TeutonicKnight",
      "Berserk",
      "Samurai",
      "JaguarWarrior",
      "Janissary",
      "OrganGun",
      "Slinger",
      "Boyar",
      "Conquistador",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  EagleScout: {
    units: ["EagleScout", "EagleWarrior", "EliteEagleWarrior"],
    counteredBy: [
      "Militia",
      "HandCannoneer",
      "KarambitWarrior",
      "Berserk",
      "Samurai",
      "Huskarl",
      "WoadRaider",
      "ThrowingAxeman",
      "Slinger",
      "Janissary",
      "OrganGun",
      "Boyar",
      "Cataphract",
    ],
    upgrades: [
      "ElDorado",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "GarlandWars",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      "FabricShields",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  Spearman: {
    units: ["Spearman", "Pikeman", "Halberdier"],
    counteredBy: [
      "Militia",
      "Archer",
      "HandCannoneer",
      "Skirmisher",
      "Scorpion",
      "KarambitWarrior",
      "ShotelWarrior",
      "Kamayuk",
      "FlemishMilitia",
      "Berserk",
      "WoadRaider",
      "ThrowingAxeman",
      "ChuKoNu",
      "Gbeto",
      "Janissary",
      "OrganGun",
      "Slinger",
      "Mameluke",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "GarlandWars",
      "WootzSteel",
      "Druzhina",
      "Chieftains",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "TowerShields",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Perfusion",
      "Kshatriyas",
      "Stronghold-Infantry",
    ],
  },
  Militia: {
    units: [
      "Militia",
      "ManAtArms",
      "LongSwordsman",
      "TwoHandedSwordsman",
      "Champion",
    ],
    counteredBy: [
      "Archer",
      "HandCannoneer",
      "CavalryArcher",
      "Scorpion",
      "TeutonicKnight",
      "JaguarWarrior",
      "Slinger",
      "ChuKoNu",
      "Janissary",
      "OrganGun",
      "Cataphract",
      "Boyar",
      "Conquistador",
      "WarWagon",
      "BallistaElephant",
      "Genitour",
      "Kipchak",
      "Mangudai",
    ],
    upgrades: [
      "Fereters-HP",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "GarlandWars",
      "Druzhina",
      "Chieftains",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Gambesons",
      "Bagains",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Perfusion",
      "Supplies",
      "ForcedLevy",
      "Comitatenses",
      "WootzSteel",
      "Kshatriyas",
    ],
  },
  Legionary: {
    units: ["Legionary"],
    counteredBy: [
      "Archer",
      "HandCannoneer",
      "CavalryArcher",
      "Scorpion",
      "TeutonicKnight",
      "JaguarWarrior",
      "Slinger",
      "ChuKoNu",
      "Janissary",
      "OrganGun",
      "Cataphract",
      "Boyar",
      "Conquistador",
      "WarWagon",
      "BallistaElephant",
      "Genitour",
      "Kipchak",
      "Mangudai",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Conscription",
      "Comitatenses",
      "Centurion",
      "Stronghold-Infantry",
    ],
  },
  Centurion: {
    units: ["Centurion", "EliteCenturion"],
    unique: true,
    counteredBy: [],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Comitatenses",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Conscription",
      "Kasbah",
    ],
  },
  Dromon: {
    units: ["Dromon"],
    counteredBy: [],
    upgrades: [
      "SiegeEngineers-20-1",
      "CilicianFleet-Range",
      "Chemistry",
      "Careening",
      "DryDock",
      "Devotion",
      "Faith",
      "Heresy",
      "Shipwright",
      "GreekFire-Dromon",
    ],
  },
  Keshik: {
    units: ["Keshik", "EliteKeshik"],
    unique: true,
    civ: "Tatars",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Knight",
      "Kamayuk",
      "Berserk",
      "TeutonicKnight",
      "GenoeseCrossbowman",
      "Mameluke",
      "CamelRider",
      "WarElephant",
      "Boyar",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Conscription",
    ],
  },
  Leitis: {
    units: ["Leitis", "EliteLeitis"],
    unique: true,
    civ: "Lithuanians",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Monk",
      "CamelRider",
      "Kamayuk",
      "GenoeseCrossbowman",
      "Mameluke",
      "WarElephant",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  Konnik: {
    related: ["KonnikDismounted"],
    units: ["Konnik", "EliteKonnik"],
    unique: true,
    civ: "Bulgarians",
    counteredBy: [
      "TeutonicKnight",
      "Kamayuk",
      "GenoeseCrossbowman",
      "Boyar",
      "WarElephant",
      "BattleElephant",
      "Mameluke",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Stirrups",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  KonnikDismounted: {
    related: ["Konnik"],
    units: ["KonnikDismounted", "EliteKonnikDismounted"],
    unique: true,
    civ: "Bulgarians",
    counteredBy: [
      "TeutonicKnight",
      "Kamayuk",
      "GenoeseCrossbowman",
      "Boyar",
      "WarElephant",
      "BattleElephant",
      "Mameluke",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Squires",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  Boyar: {
    units: ["Boyar", "EliteBoyar"],
    unique: true,
    civ: "Slavs",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Archer",
      "Monk",
      "Missionary",
      "CamelRider",
      "Scorpion",
      "TeutonicKnight",
      "Berserk",
      "Kamayuk",
      "WarElephant",
      "Mameluke",
      "Leitis",
      "Obuch",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Conscription",
    ],
  },
  MagyarHuszar: {
    units: ["MagyarHuszar", "EliteMagyarHuszar"],
    unique: true,
    civ: "Magyars",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "CamelRider",
      "EagleScout",
      "Berserk",
      "TeutonicKnight",
      "Kamayuk",
      "GenoeseCrossbowman",
      "Mameluke",
      "Boyar",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Heresy",
      "Conscription",
      "CorvinianArmy",
    ],
  },
  Tarkan: {
    units: ["Tarkan", "EliteTarkan"],
    unique: true,
    civ: "Huns",
    counteredBy: [
      "Militia",
      "Spearman",
      "FlemishMilitia",
      "CamelRider",
      "Knight",
      "GenoeseCrossbowman",
      "Mameluke",
      "Konnik",
      "Boyar",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Marauders",
    ],
  },
  Mameluke: {
    units: ["Mameluke", "EliteMameluke"],
    unique: true,
    civ: "Saracens",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "GenoeseCrossbowman",
      "Kamayuk",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  WarElephant: {
    units: ["WarElephant", "EliteWarElephant"],
    unique: true,
    civ: "Persians",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Monk",
      "Missionary",
      "CamelRider",
      "Samurai",
      "Kamayuk",
      "ChuKoNu",
      "GenoeseCrossbowman",
      "Mameluke",
      "CamelArcher",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Conscription",
    ],
  },
  Cataphract: {
    units: ["Cataphract", "EliteCataphract"],
    unique: true,
    civ: "Byzantines",
    counteredBy: ["Knight", "WarElephant", "Boyar"],
    upgrades: [
      "Forging",
      "IronCasting",
      "Logistica",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  SteppeLancer: {
    units: ["SteppeLancer", "EliteSteppeLancer"],
    counteredBy: [
      "Militia",
      "Spearman",
      "FlemishMilitia",
      "Knight",
      "CamelRider",
      "Boyar",
      "Konnik",
      "Mameluke",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "SilkArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "SteppeHusbandry",
    ],
  },
  BattleElephant: {
    units: ["BattleElephant", "EliteBattleElephant"],
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Monk",
      "CamelRider",
      "CavalryArcher", // Maybe (EDIT BY FifthSense: https://ageofempires.fandom.com/wiki/Battle_Elephant states they do)
      "Scorpion",
      "Kamayuk",
      "GenoeseCrossbowman",
      "Mameluke",
      "WarElephant",
    ],
    upgrades: [
      "Bloodlines",
      "Chatras",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ManipurCavalry",
      "WootzSteel",
      "Paiks",
      "TuskSwords",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Howdah",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy-Malay",
      "Conscription",
      "MedicalCorps",
    ],
  },
  CamelRider: {
    units: [
      "CamelScout",
      "CamelRider",
      "HeavyCamelRider",
      "ImperialCamelRider",
    ],
    counteredBy: [
      "Militia",
      "Spearman",
      "FlemishMilitia",
      "Serjeant",
      "Berserk",
      "TeutonicKnight",
      "GenoeseCrossbowman",
      "Cataphract",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Farimba",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "FrontierGuards",
      "Kshatriyas",
      "MaghrebiCamels",
      "RoyalHeirs",
    ],
  },
  Knight: {
    units: ["Knight", "Cavalier", "Paladin", "Savar"],
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "CamelRider",
      "Monk",
      "Kamayuk",
      "Berserk",
      "TeutonicKnight",
      "GenoeseCrossbowman",
      "ThrowingAxeman",
      "Mameluke",
      "WarElephant",
      "Boyar",
    ],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Farimba",
      "ManipurCavalry",
      "Comitatenses",
      "Stirrups",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Chivalry",
      "SzlachtaPrivileges",
      "Hauberk",
      "AznauriCavalry",
    ],
  },
  XolotlWarrior: {
    units: ["XolotlWarrior"],
    unique: true,
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Monk",
      "CamelRider",
      "Kamayuk",
      "Berserk",
      "TeutonicKnight",
      "GenoeseCrossbowman",
      "Boyar",
      "Mameluke",
      "WarElephant",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Devotion",
      "Faith",
      "Heresy",
    ],
  },
  ScoutCavalry: {
    units: ["ScoutCavalry", "LightCavalry", "Hussar", "WingedHussar"],
    counteredBy: [
      "Militia",
      "Spearman",
      "FlemishMilitia",
      "Coustillier",
      "Skirmisher",
      "CamelRider",
      "Knight",
      "EagleScout",
      "WoadRaider",
      "Berserk",
      "Serjeant",
      "ShotelWarrior",
      "Kamayuk",
      "Huskarl",
      "GenoeseCrossbowman",
      "ThrowingAxeman",
      "Tarkan",
      "Mameluke",
      "SteppeLancer",
      "Cataphract",
    ],
    upgrades: [
      // 'FeudalAge-ScoutCavalry',
      // 'CastleAge-ScoutCavalry',
      // 'ImperialAge-ScoutCavalry',
      // 'ImperialAge-LightCavalry',
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Farimba",
      "ManipurCavalry",
      "Stirrups",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "SilkArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Chivalry",
      "SteppeHusbandry",
      "LechiticLegacy",
      "WootzSteel",
      "Kshatriyas",
      "AznauriCavalry",
    ],
  },
  Kipchak: {
    units: ["Kipchak", "EliteKipchak"],
    unique: true,
    civ: "Cumans",
    counteredBy: [
      "Skirmisher",
      "CamelRider",
      "Mangonel",
      "Scorpion",
      "Kamayuk",
      "Huskarl",
      "EagleScout",
      "RattanArcher",
      "GenoeseCrossbowman",
      "Genitour",
    ],
    upgrades: [
      "Bloodlines",
      "Sipahi",
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ThumbRing-11",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "ParthianTactics",
      "RecurveBow",
      "SilkArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Kasbah",
    ],
  },
  RattanArcher: {
    units: ["RattanArcher", "EliteRattanArcher"],
    unique: true,
    civ: "Vietnamese",
    counteredBy: [
      "ScoutCavalry",
      "CamelRider",
      "Knight",
      "Mangonel",
      "Scorpion",
      "Huskarl",
      "EagleScout",
      "Boyar",
      "MagyarHuszar",
      "Coustillier",
      "Mameluke",
      "Cataphract",
      "SteppeLancer",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ThumbRing-18",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Devotion",
      "Faith",
      "Conscription",
    ],
  },
  Genitour: {
    units: ["Genitour", "EliteGenitour"],
    unique: true,
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "CamelRider",
      "Mangonel",
      "Scorpion",
      "Huskarl",
      "EagleScout",
      "GenoeseCrossbowman",
    ],
    upgrades: [
      "Bloodlines",
      "Sipahi",
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "Atlatl",
      "RecurveBow",
      "AndeanSling",
      "ThumbRing-No",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "SilkArmor",
      "TowerShields",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "HulcheJavelineers",
    ],
  },
  CamelArcher: {
    units: ["CamelArcher", "EliteCamelArcher"],
    unique: true,
    civ: "Berbers",
    counteredBy: [
      "Skirmisher",
      "CamelRider",
      "Mangonel",
      "EagleScout",
      "Huskarl",
    ],
    upgrades: [
      "Bloodlines",
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ThumbRing-18",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Kasbah",
      "MaghrebiCamels",
    ],
  },
  GenoeseCrossbowman: {
    units: ["GenoeseCrossbowman", "EliteGenoeseCrossbowman"],
    unique: true,
    civ: "Italians",
    counteredBy: [
      "Archer",
      "Skirmisher",
      "Mangonel",
      "Scorpion",
      "EagleScout",
      "Huskarl",
      "PlumedArcher",
      "ChuKoNu",
      "RattanArcher",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ThumbRing-18-No",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Pavise",
      "Devotion",
      "Faith",
      "Conscription",
    ],
  },
  ElephantArcher: {
    units: ["ElephantArcher", "EliteElephantArcher"],
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Monk",
      "Skirmisher",
      "CamelRider",
      "Kamayuk",
      "Berserk",
      "Huskarl",
      "EagleScout",
      "GenoeseCrossbowman",
      "Mameluke",
    ],
    upgrades: [
      "Bloodlines",
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ThumbRing-18",
      "Paiks",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "ParthianTactics-Bengalis",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy-Gurjaras",
      "Conscription",
      "FrontierGuards",
      "MedicalCorps",
      "Kshatriyas",
    ],
  },
  WarWagon: {
    units: ["WarWagon", "EliteWarWagon"],
    unique: true,
    civ: "Koreans",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Monk",
      "Skirmisher",
      "Knight",
      "Mangonel",
      "Kamayuk",
      "Huskarl",
      "EagleScout",
      "GenoeseCrossbowman",
      "Mameluke",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ThumbRing-11-No",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Conscription",
    ],
  },
  Mangudai: {
    units: ["Mangudai", "EliteMangudai"],
    unique: true,
    civ: "Mongols",
    counteredBy: [
      "Spearman",
      "FlemishMilitia",
      "Skirmisher",
      "CamelRider",
      "Knight",
      "EagleScout",
      "Kamayuk",
      "Huskarl",
      "GenoeseCrossbowman",
      "Mameluke",
      "CamelArcher",
    ],
    upgrades: [
      "Bloodlines",
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ThumbRing-18",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "ParthianTactics",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  ChuKoNu: {
    units: ["ChuKoNu", "EliteChuKoNu"],
    unique: true,
    civ: "Chinese",
    counteredBy: [
      "Skirmisher",
      "Knight",
      "Mangonel",
      "Scorpion",
      "EagleScout",
      "Huskarl",
      "Boyar",
      "Cataphract",
      "Genitour",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "Rocketry-2",
      "ThumbRing-25",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Devotion",
      "Faith",
      "Conscription",
    ],
  },
  Longbowman: {
    units: ["Longbowman", "EliteLongbowman"],
    unique: true,
    civ: "Britons",
    counteredBy: [
      "Skirmisher",
      "Knight",
      "Scorpion",
      "EagleScout",
      "Huskarl",
      "Boyar",
      "Cataphract",
      "Genitour",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Yeomen",
      "Chemistry",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Devotion",
      "Faith",
      "Conscription",
    ],
  },
  CavalryArcher: {
    units: ["CavalryArcher", "HeavyCavalryArcher"],
    counteredBy: [
      //'Spearman',  Maybe 'FS-EDIT: neither the wiki nor the spreadsheet considers them to be a counter'
      "FlemishMilitia",
      "Coustillier",
      "Skirmisher",
      "Knight",
      "CamelRider",
      "Mangonel",
      "BatteringRam",
      "EagleScout",
      "Kamayuk",
      "Huskarl",
      "RattanArcher",
      "GenoeseCrossbowman",
      "CamelArcher",
    ],
    upgrades: [
      "Bloodlines",
      "Sipahi",
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ParthianTactics",
      "RecurveBow",
      "ThumbRing-11",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "SilkArmor",
      "Husbandry",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "SteppeHusbandry",
    ],
  },
  Skirmisher: {
    units: ["Skirmisher", "EliteSkirmisher", "ImperialSkirmisher"],
    counteredBy: [
      "Militia",
      "Knight",
      "ScoutCavalry",
      "CamelRider",
      "Mangonel",
      "Scorpion",
      "BatteringRam",
      "EagleScout",
      "BattleElephant",
      "WarElephant",
      "Tarkan",
      "Konnik",
      "KonnikDismounted",
      "Serjeant",
      "FlemishMilitia",
      "Boyar",
      "MagyarHuszar",
      "Coustillier",
      "Mameluke",
      "Cataphract",
      "SteppeLancer",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "Atlatl",
      "Yeomen",
      "AndeanSling",
      "ThumbRing-No",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "TowerShields",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "HulcheJavelineers",
      "Kshatriyas",
    ],
  },
  Archer: {
    units: ["Archer", "Crossbowman", "Arbalester"],
    counteredBy: [
      "Skirmisher",
      "Knight",
      "ScoutCavalry",
      "Scorpion",
      "Mangonel",
      "BombardCannon",
      "BatteringRam",
      "EagleScout",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "Yeomen",
      "ThumbRing-18",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Pavise",
      "Devotion",
      "Faith",
      "Heresy",
      "Kamandaran",
      "Conscription",
      "Bogsveigar",
    ],
  },
  PlumedArcher: {
    units: ["PlumedArcher", "ElitePlumedArcher"],
    unique: true,
    civ: "Mayans",
    counteredBy: [
      "Skirmisher",
      "Knight",
      "ScoutCavalry",
      "Mangonel",
      "Scorpion",
      "Huskarl",
      "EagleScout",
      "RattanArcher",
      "Genitour",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "ThumbRing-18",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  Slinger: {
    units: ["Slinger"],
    unique: true,
    counteredBy: [
      "Skirmisher",
      "Knight",
      "ScoutCavalry",
      "Mangonel",
      "Scorpion",
      "Huskarl",
      "RattanArcher",
      "Genitour",
      "Tarkan",
      "Boyar",
      "MagyarHuszar",
      "Coustillier",
      "Mameluke",
      "Cataphract",
      "SteppeLancer",
    ],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "AndeanSling-1",
      "AndeanSling",
      "ThumbRing-No",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "FabricShields",
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
    ],
  },
  Kamayuk: {
    units: ["Kamayuk", "EliteKamayuk"],
    unique: true,
    civ: "Incas",
    counteredBy: [
      "HandCannoneer",
      "Monk",
      "Mangonel",
      "Scorpion",
      "TeutonicKnight",
      "Slinger",
      "Janissary",
      "OrganGun",
      "PlumedArcher",
      "Cataphract",
    ],
    upgrades: [
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "FabricShields",
      "Squires",
      // 'Tracking',
      "Devotion",
      "Faith",
      "Heresy",
      "Conscription",
      "Stronghold-Infantry",
    ],
  },
  CompositeBowman: {
    units: ["CompositeBowman", "EliteCompositeBowman"],
    unique: true,
    civ: "Armenians",
    counteredBy: [],
    upgrades: [
      "Fletching",
      "BodkinArrow",
      "Bracer",
      "Chemistry",
      "Ballistics",
      "PaddedArcherArmor",
      "LeatherArcherArmor",
      "RingArcherArmor",
      "Devotion",
      "Faith",
      "Conscription",
      "Kasbah",
    ],
  },
  Monaspa: {
    units: ["Monaspa", "EliteMonaspa"],
    unique: true,
    civ: "Georgians",
    counteredBy: [],
    upgrades: [
      "Bloodlines",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "ScaleBardingArmor",
      "ChainBardingArmor",
      "PlateBardingArmor",
      "Devotion",
      "Faith",
      "Heresy",
      "Husbandry",
      "Conscription",
      "Kasbah",
      "AznauriCavalry",
    ],
  },
  WarriorPriest: {
    units: ["WarriorPriest"],
    unique: true,
    civ: "Armenians",
    counteredBy: [
      // Infantry
      // 'ScoutCavalry',
      // 'EagleScout',
      // 'Samurai',
      // 'Cataphract',
      // 'JaguarWarrior',
      // 'TeutonicKnight',
      // 'UrumiSwordsman',
      // 'CavalryArcher',
      // 'Mangudai',
    ],
    upgrades: [
      "Sanctity",
      "Fereters",
      "Forging",
      "IronCasting",
      "BlastFurnace",
      "Arson",
      "ScaleMailArmor",
      "ChainMailArmor",
      "PlateMailArmor",
      "Devotion",
      "Faith",
      "Heresy",
      // 'Tracking',
      "Squires",
      "Fervor",
      "Stronghold-Infantry",
    ],
  },
};

export type unitLinesType = {
  [key: string]: {
    units: string[];
    civ?: string;
    counteredBy?: string[];
    upgrades?: string[];
    unique?: boolean;
    related?: string[];
  };
};
