insert into unit_name (unit_id, locale, name) values
('FireLancer', 'en', 'Fire Lancer'),
('FireLancer', 'es', 'Lancero incendiario'),
('EliteFireLancer', 'en', 'Elite Fire Lancer'),
('EliteFireLancer', 'es', 'Lancero incendiario de élite'),
('RocketCart', 'en', 'Rocket Cart'),
('RocketCart', 'es', 'Carro de cohetes'),
('HeavyRocketCart', 'en', 'Heavy Rocket Cart'),
('HeavyRocketCart', 'es', 'Carro de cohetes pesado'),
('LouChuan', 'en', 'Lou Chuan'),
('LouChuan', 'es', 'Lou Chuan'),
('IronPagoda', 'en', 'Iron Pagoda'),
('IronPagoda', 'es', 'Pagoda de hierro'),
('EliteIronPagoda', 'en', 'Elite Iron Pagoda'),
('EliteIronPagoda', 'es', 'Pagoda de hierro de élite'),
('LiaoDao', 'en', 'Liao Dao'),
('LiaoDao', 'es', 'Liao Dao'),
('EliteLiaoDao', 'en', 'Elite Liao Dao'),
('EliteLiaoDao', 'es', 'Liao Dao de élite'),
('WhiteFeatherGuard', 'en', 'White Feather Guard'),
('WhiteFeatherGuard', 'es', 'Guardia de la pluma blanca'),
('EliteWhiteFeatherGuard', 'en', 'Elite White Feather Guard'),
('EliteWhiteFeatherGuard', 'es', 'Guardia de la pluma blanca de élite'),
('TigerCavalry', 'en', 'Tiger Cavalry'),
('TigerCavalry', 'es', 'Caballería tigresa'),
('EliteTigerCavalry', 'en', 'Elite Tiger Cavalry'),
('EliteTigerCavalry', 'es', 'Caballería tigresa de élite'),
('HeiGuangCavalry', 'en', 'Hei Guang Cavalry'),
('HeiGuangCavalry', 'es', 'Caballería de Hei Guang'),
('HeavyHeiGuangCavalry', 'en', 'Heavy Hei Guang Cavalry'),
('HeavyHeiGuangCavalry', 'es', 'Caballería pesada de Hei Guang'),
('FireArcher', 'en', 'Fire Archer'),
('FireArcher', 'es', 'Arquero de fuego'),
('EliteFireArcher', 'en', 'Elite Fire Archer'),
('EliteFireArcher', 'es', 'Arquero de fuego de élite'),
('Grenadier', 'en', 'Grenadier'),
('Grenadier', 'es', 'Granadero'),
('MountedTrebuchet', 'en', 'Mounted Trebuchet'),
('MountedTrebuchet', 'es', 'Trebuchet montado'),
('TractionTrebuchet', 'en', 'Traction Trebuchet'),
('TractionTrebuchet', 'es', 'Trebuchet de tracción'),
('WarChariot', 'en', 'War Chariot (Focus Fire)'),
('WarChariot', 'es', 'Carro de guerra (disparo concentrado)'),
('XianbeiRaider', 'en', 'Xianbei Raider'),
('XianbeiRaider', 'es', 'Saqueador xianbei'),
('JianSwordsman', 'en', 'Jian Swordsman'),
('JianSwordsman', 'es', 'Espadachín de Jian'),
('DragonShip', 'en', 'Dragon Ship'),
('DragonShip', 'es', 'Bote dragón'),
('LiuBei', 'en', 'Liu Bei'),
('LiuBei', 'es', 'Liu Bei'),
('CaoCao', 'en', 'Cao Cao'),
('CaoCao', 'es', 'Cao Cao'),
('SunJian', 'en', 'Sun Jian'),
('SunJian', 'es', 'Sun Jian'),
('Ghulam', 'en', 'Ghulam'),
('Ghulam', 'es', 'Ghulam'),
('EliteGhulam', 'en', 'Elite Ghulam'),
('EliteGhulam', 'es', 'Ghulam de élite'),
('ShrivamshaRider', 'en', 'Shrivamsha Rider'),
('ShrivamshaRider', 'es', 'Jinete shrivamsha'),
('EliteShrivamshaRider', 'en', 'Elite Shrivamsha Rider'),
('EliteShrivamshaRider', 'es', 'Jinete shrivamsha de élite'),
('ChakramThrower', 'en', 'Chakram Thrower'),
('ChakramThrower', 'es', 'Lanzador de chakrams'),
('EliteChakramThrower', 'en', 'Elite Chakram Thrower'),
('EliteChakramThrower', 'es', 'Lanzador de chakrams de élite'),
('Thirisadai', 'en', 'Thirisadai'),
('Thirisadai', 'es', 'Thirisadai'),
('UrumiSwordsman', 'en', 'Urumi Swordsman'),
('UrumiSwordsman', 'es', 'Espadachín urumi'),
('EliteUrumiSwordsman', 'en', 'Elite Urumi Swordsman'),
('EliteUrumiSwordsman', 'es', 'Espadachín urumi de élite'),
('ArmoredElephant', 'en', 'Armored Elephant'),
('ArmoredElephant', 'es', 'Elefante blindado'),
('SiegeElephant', 'en', 'Siege Elephant'),
('SiegeElephant', 'es', 'Elefante de asedio'),
('Ratha', 'en', 'Ratha'),
('Ratha', 'es', 'Ratha'),
('EliteRatha', 'en', 'Elite Ratha'),
('EliteRatha', 'es', 'Ratha de élite'),
('Obuch', 'en', 'Obuch'),
('Obuch', 'es', 'Martillo de guerra'),
('EliteObuch', 'en', 'Elite Obuch'),
('EliteObuch', 'es', 'Martillo de guerra de élite'),
('HussiteWagon', 'en', 'Hussite Wagon'),
('HussiteWagon', 'es', 'Carro de guerra husita'),
('EliteHussiteWagon', 'en', 'Elite Hussite Wagon'),
('EliteHussiteWagon', 'es', 'Carro de guerra husita de élite'),
('Coustillier', 'en', 'Coustillier'),
('Coustillier', 'es', 'Costiller'),
('EliteCoustillier', 'en', 'Elite Coustillier'),
('EliteCoustillier', 'es', 'Costiller de élite'),
('Serjeant', 'en', 'Serjeant'),
('Serjeant', 'es', 'Serjeant'),
('EliteSerjeant', 'en', 'Elite Serjeant'),
('EliteSerjeant', 'es', 'Serjeant de élite'),
('FlemishMilitia', 'en', 'Flemish Militia'),
('FlemishMilitia', 'es', 'Milicia flamenca'),
('TradeCart', 'en', 'Trade Cart'),
('TradeCart', 'es', 'Carreta de mercancías'),
('TradeCog', 'en', 'Trade Cog'),
('TradeCog', 'es', 'Barca mercante'),
('FishingShip', 'en', 'Fishing Ship'),
('FishingShip', 'es', 'Pesquero'),
('TransportShip', 'en', 'Transport Ship'),
('TransportShip', 'es', 'Barco transporte'),
('Villager', 'en', 'Villager'),
('Villager', 'es', 'Aldeano'),
('Missionary', 'en', 'Missionary'),
('Missionary', 'es', 'Misionero'),
('Monk', 'en', 'Monk'),
('Monk', 'es', 'Monje'),
('DemolitionRaft', 'en', 'Demolition Raft'),
('DemolitionRaft', 'es', 'Balsa de demolición'),
('DemolitionShip', 'en', 'Demolition Ship'),
('DemolitionShip', 'es', 'Buque de demolición'),
('HeavyDemolitionShip', 'en', 'Heavy Demolition Ship'),
('HeavyDemolitionShip', 'es', 'Buque dem. pesado'),
('FireGalley', 'en', 'Fire Galley'),
('FireGalley', 'es', 'Galera incendiaria'),
('FireShip', 'en', 'Fire Ship'),
('FireShip', 'es', 'Barco incendiario'),
('FastFireShip', 'en', 'Fast Fire Ship'),
('FastFireShip', 'es', 'Barco incendiario rápido'),
('Galley', 'en', 'Galley'),
('Galley', 'es', 'Galera'),
('WarGalley', 'en', 'War Galley'),
('WarGalley', 'es', 'Galera de guerra'),
('Galleon', 'en', 'Galleon'),
('Galleon', 'es', 'Galeón'),
('CannonGalleon', 'en', 'Cannon Galleon'),
('CannonGalleon', 'es', 'Galeón artillado'),
('EliteCannonGalleon', 'en', 'Elite Cannon Galleon'),
('EliteCannonGalleon', 'es', 'Galeón artillado élite'),
('Arambai', 'en', 'Arambai'),
('Arambai', 'es', 'Arambai'),
('EliteArambai', 'en', 'Elite Arambai'),
('EliteArambai', 'es', 'Arambai de élite'),
('OrganGun', 'en', 'Organ Gun'),
('OrganGun', 'es', 'Cañón de salvas'),
('EliteOrganGun', 'en', 'Elite Organ Gun'),
('EliteOrganGun', 'es', 'Cañón de salvas de élite'),
('Caravel', 'en', 'Caravel'),
('Caravel', 'es', 'Carabela'),
('EliteCaravel', 'en', 'Elite Caravel'),
('EliteCaravel', 'es', 'Carabela de élite'),
('SiegeTower', 'en', 'Siege Tower'),
('SiegeTower', 'es', 'Torre de asedio'),
('Conquistador', 'en', 'Conquistador'),
('Conquistador', 'es', 'Conquistador'),
('EliteConquistador', 'en', 'Elite Conquistador'),
('EliteConquistador', 'es', 'Conquistador de élite'),
('TurtleShip', 'en', 'Turtle Ship'),
('TurtleShip', 'es', 'Barco tortuga'),
('EliteTurtleShip', 'en', 'Elite Turtle Ship'),
('EliteTurtleShip', 'es', 'Barco tortuga de élite'),
('Longboat', 'en', 'Longboat'),
('Longboat', 'es', 'Drakkar'),
('EliteLongboat', 'en', 'Elite Longboat'),
('EliteLongboat', 'es', 'Drakkar de élite'),
('Janissary', 'en', 'Janissary'),
('Janissary', 'es', 'Jenízaro'),
('EliteJanissary', 'en', 'Elite Janissary'),
('EliteJanissary', 'es', 'Jenízaro de élite'),
('BallistaElephant', 'en', 'Ballista Elephant'),
('BallistaElephant', 'es', 'Elefante con balista'),
('EliteBallistaElephant', 'en', 'Elite Ballista Elephant'),
('EliteBallistaElephant', 'es', 'Elefante con balista de élite'),
('FlamingCamel', 'en', 'Flaming Camel'),
('FlamingCamel', 'es', 'Camello llameante'),
('Petard', 'en', 'Petard'),
('Petard', 'es', 'Petardo'),
('Trebuchet', 'en', 'Trebuchet'),
('Trebuchet', 'es', 'Lanzapiedras'),
('BombardCannon', 'en', 'Bombard Cannon'),
('BombardCannon', 'es', 'Cañón de asedio'),
('Houfnice', 'en', 'Houfnice'),
('Houfnice', 'es', 'Obús'),
('Mangonel', 'en', 'Mangonel'),
('Mangonel', 'es', 'Mangana'),
('Onager', 'en', 'Onager'),
('Onager', 'es', 'Onagro'),
('SiegeOnager', 'en', 'Siege Onager'),
('SiegeOnager', 'es', 'Onagro de asedio'),
('BatteringRam', 'en', 'Battering Ram'),
('BatteringRam', 'es', 'Ariete'),
('CappedRam', 'en', 'Capped Ram'),
('CappedRam', 'es', 'Ariete cubierto'),
('SiegeRam', 'en', 'Siege Ram'),
('SiegeRam', 'es', 'Ariete de asedio'),
('Scorpion', 'en', 'Scorpion'),
('Scorpion', 'es', 'Escorpión'),
('HeavyScorpion', 'en', 'Heavy Scorpion'),
('HeavyScorpion', 'es', 'Escorpión pesado'),
('HandCannoneer', 'en', 'Hand Cannoneer'),
('HandCannoneer', 'es', 'Artillero manual'),
('KarambitWarrior', 'en', 'Karambit Warrior'),
('KarambitWarrior', 'es', 'Recluta con karambit'),
('EliteKarambitWarrior', 'en', 'Elite Karambit Warrior'),
('EliteKarambitWarrior', 'es', 'Recluta con karambit de élite'),
('Gbeto', 'en', 'Gbeto'),
('Gbeto', 'es', 'Guardiana gbeto'),
('EliteGbeto', 'en', 'Elite Gbeto'),
('EliteGbeto', 'es', 'Guardiana gbeto de élite'),
('ShotelWarrior', 'en', 'Shotel Warrior'),
('ShotelWarrior', 'es', 'Shotelai'),
('EliteShotelWarrior', 'en', 'Elite Shotel Warrior'),
('EliteShotelWarrior', 'es', 'Shotelai de élite'),
('Condottiero', 'en', 'Condottiero'),
('Condottiero', 'es', 'Condotiero'),
('JaguarWarrior', 'en', 'Jaguar Warrior'),
('JaguarWarrior', 'es', 'Guerrero jaguar'),
('EliteJaguarWarrior', 'en', 'Elite Jaguar Warrior'),
('EliteJaguarWarrior', 'es', 'Guerrero jaguar de élite'),
('Berserk', 'en', 'Berserk'),
('Berserk', 'es', 'Berserker'),
('EliteBerserk', 'en', 'Elite Berserk'),
('EliteBerserk', 'es', 'Berserker de élite'),
('TeutonicKnight', 'en', 'Teutonic Knight'),
('TeutonicKnight', 'es', 'Cab. Orden Teutónica'),
('EliteTeutonicKnight', 'en', 'Elite Teutonic Knight'),
('EliteTeutonicKnight', 'es', 'Cab O. Teutónica élite'),
('Samurai', 'en', 'Samurai'),
('Samurai', 'es', 'Samurai'),
('EliteSamurai', 'en', 'Elite Samurai'),
('EliteSamurai', 'es', 'Samurai de élite'),
('Huskarl', 'en', 'Huskarl'),
('Huskarl', 'es', 'Huscarle'),
('EliteHuskarl', 'en', 'Elite Huskarl'),
('EliteHuskarl', 'es', 'Huscarle de élite'),
('ThrowingAxeman', 'en', 'Throwing Axeman'),
('ThrowingAxeman', 'es', 'Lanzador de hachas'),
('EliteThrowingAxeman', 'en', 'Elite Throwing Axeman'),
('EliteThrowingAxeman', 'es', 'Lanzador hachas élite'),
('WoadRaider', 'en', 'Woad Raider'),
('WoadRaider', 'es', 'Incursor azul'),
('EliteWoadRaider', 'en', 'Elite Woad Raider'),
('EliteWoadRaider', 'es', 'Incursor azul de élite'),
('EagleScout', 'en', 'Eagle Scout'),
('EagleScout', 'es', 'Explorador águila'),
('EagleWarrior', 'en', 'Eagle Warrior'),
('EagleWarrior', 'es', 'Guerrero águila'),
('EliteEagleWarrior', 'en', 'Elite Eagle Warrior'),
('EliteEagleWarrior', 'es', 'Guerrero águila de élite'),
('Spearman', 'en', 'Spearman'),
('Spearman', 'es', 'Lancero'),
('Pikeman', 'en', 'Pikeman'),
('Pikeman', 'es', 'Piquero'),
('Halberdier', 'en', 'Halberdier'),
('Halberdier', 'es', 'Alabardero'),
('Militia', 'en', 'Militia'),
('Militia', 'es', 'Milicia'),
('ManAtArms', 'en', 'Man-at-Arms'),
('ManAtArms', 'es', 'Hombre de armas'),
('LongSwordsman', 'en', 'Long Swordsman'),
('LongSwordsman', 'es', 'Espad. espada larga'),
('TwoHandedSwordsman', 'en', 'Two-Handed Swordsman'),
('TwoHandedSwordsman', 'es', 'Espad. de mandoble'),
('Champion', 'en', 'Champion'),
('Champion', 'es', 'Campeón'),
('Keshik', 'en', 'Keshik'),
('Keshik', 'es', 'Keshik'),
('EliteKeshik', 'en', 'Elite Keshik'),
('EliteKeshik', 'es', 'Keshik de élite'),
('Leitis', 'en', 'Leitis'),
('Leitis', 'es', 'Leitis'),
('EliteLeitis', 'en', 'Elite Leitis'),
('EliteLeitis', 'es', 'Leitis de élite'),
('Konnik', 'en', 'Konnik'),
('Konnik', 'es', 'Konnik'),
('EliteKonnik', 'en', 'Elite Konnik'),
('EliteKonnik', 'es', 'Konnik de élite'),
('KonnikDismounted', 'en', 'Konnik (Dismounted)'),
('KonnikDismounted', 'es', 'Konnik (desmontado)'),
('EliteKonnikDismounted', 'en', 'Elite Konnik (Dismounted)'),
('EliteKonnikDismounted', 'es', 'Konnik de élite (desmontado)'),
('Boyar', 'en', 'Boyar'),
('Boyar', 'es', 'Boyardo'),
('EliteBoyar', 'en', 'Elite Boyar'),
('EliteBoyar', 'es', 'Boyardo de élite'),
('MagyarHuszar', 'en', 'Magyar Huszar'),
('MagyarHuszar', 'es', 'Huszár magiar'),
('EliteMagyarHuszar', 'en', 'Elite Magyar Huszar'),
('EliteMagyarHuszar', 'es', 'Huszár magiar de élite'),
('Tarkan', 'en', 'Tarkan'),
('Tarkan', 'es', 'Tarcano'),
('EliteTarkan', 'en', 'Elite Tarkan'),
('EliteTarkan', 'es', 'Tarcano de élite'),
('Mameluke', 'en', 'Mameluke'),
('Mameluke', 'es', 'Mameluco'),
('EliteMameluke', 'en', 'Elite Mameluke'),
('EliteMameluke', 'es', 'Mameluco de élite'),
('WarElephant', 'en', 'War Elephant'),
('WarElephant', 'es', 'Elefante de guerra'),
('EliteWarElephant', 'en', 'Elite War Elephant'),
('EliteWarElephant', 'es', 'Elefante guerra élite'),
('Cataphract', 'en', 'Cataphract'),
('Cataphract', 'es', 'Catafracta'),
('EliteCataphract', 'en', 'Elite Cataphract'),
('EliteCataphract', 'es', 'Catafracta de élite'),
('SteppeLancer', 'en', 'Steppe Lancer'),
('SteppeLancer', 'es', 'Lancero estepario'),
('EliteSteppeLancer', 'en', 'Elite Steppe Lancer'),
('EliteSteppeLancer', 'es', 'Lancero estepario de élite'),
('BattleElephant', 'en', 'Battle Elephant'),
('BattleElephant', 'es', 'Elefante de combate'),
('EliteBattleElephant', 'en', 'Elite Battle Elephant'),
('EliteBattleElephant', 'es', 'Elefante de combate de élite'),
('CamelScout', 'en', 'Camel Scout'),
('CamelScout', 'es', 'Explorador a camello'),
('CamelRider', 'en', 'Camel Rider'),
('CamelRider', 'es', 'Jinete de camello'),
('HeavyCamelRider', 'en', 'Heavy Camel Rider'),
('HeavyCamelRider', 'es', 'Jinete de camello pesado'),
('ImperialCamelRider', 'en', 'Imperial Camel Rider'),
('ImperialCamelRider', 'es', 'Jinete de camello imperial'),
('Knight', 'en', 'Knight'),
('Knight', 'es', 'Caballero'),
('Cavalier', 'en', 'Cavalier'),
('Cavalier', 'es', 'Caballero'),
('Paladin', 'en', 'Paladin'),
('Paladin', 'es', 'Paladín'),
('Savar', 'en', 'Savar'),
('Savar', 'es', 'Savar'),
('XolotlWarrior', 'en', 'Xolotl Warrior'),
('XolotlWarrior', 'es', 'Guerrero Xólotl'),
('ScoutCavalry', 'en', 'Scout Cavalry'),
('ScoutCavalry', 'es', 'Cab. de exploración'),
('LightCavalry', 'en', 'Light Cavalry'),
('LightCavalry', 'es', 'Caballería ligera'),
('Hussar', 'en', 'Hussar'),
('Hussar', 'es', 'Húsar'),
('WingedHussar', 'en', 'Winged Hussar'),
('WingedHussar', 'es', 'Húsar alado'),
('Kipchak', 'en', 'Kipchak'),
('Kipchak', 'es', 'Kipchak'),
('EliteKipchak', 'en', 'Elite Kipchak'),
('EliteKipchak', 'es', 'Kipchak de élite'),
('RattanArcher', 'en', 'Rattan Archer'),
('RattanArcher', 'es', 'Arquero de ratán'),
('EliteRattanArcher', 'en', 'Elite Rattan Archer'),
('EliteRattanArcher', 'es', 'Arquero de ratán de élite'),
('Genitour', 'en', 'Genitour'),
('Genitour', 'es', 'Escaramuzador zenete'),
('EliteGenitour', 'en', 'Elite Genitour'),
('EliteGenitour', 'es', 'Escaramuzador zenete de élite'),
('CamelArcher', 'en', 'Camel Archer'),
('CamelArcher', 'es', 'Arquero en camello'),
('EliteCamelArcher', 'en', 'Elite Camel Archer'),
('EliteCamelArcher', 'es', 'Arquero en camello de élite'),
('GenoeseCrossbowman', 'en', 'Genoese Crossbowman'),
('GenoeseCrossbowman', 'es', 'Genovés ballestero'),
('EliteGenoeseCrossbowman', 'en', 'Elite Genoese Crossbowman'),
('EliteGenoeseCrossbowman', 'es', 'Genovés ballestero de élite'),
('ElephantArcher', 'en', 'Elephant Archer'),
('ElephantArcher', 'es', 'Arquero en elefante'),
('EliteElephantArcher', 'en', 'Elite Elephant Archer'),
('EliteElephantArcher', 'es', 'Arquero en elefante de élite'),
('WarWagon', 'en', 'War Wagon'),
('WarWagon', 'es', 'Carreta de guerra'),
('EliteWarWagon', 'en', 'Elite War Wagon'),
('EliteWarWagon', 'es', 'Carreta de guerra de élite'),
('Mangudai', 'en', 'Mangudai'),
('Mangudai', 'es', 'Mangudai'),
('EliteMangudai', 'en', 'Elite Mangudai'),
('EliteMangudai', 'es', 'Mangudai de élite'),
('ChuKoNu', 'en', 'Chu Ko Nu'),
('ChuKoNu', 'es', 'Chu ko nu'),
('EliteChuKoNu', 'en', 'Elite Chu Ko Nu'),
('EliteChuKoNu', 'es', 'Chu ko nu de élite'),
('Longbowman', 'en', 'Longbowman'),
('Longbowman', 'es', 'Arquero con arco largo'),
('EliteLongbowman', 'en', 'Elite Longbowman'),
('EliteLongbowman', 'es', 'Arq. tiro largo élite'),
('CavalryArcher', 'en', 'Cavalry Archer'),
('CavalryArcher', 'es', 'Arquero a caballo'),
('HeavyCavalryArcher', 'en', 'Heavy Cavalry Archer'),
('HeavyCavalryArcher', 'es', 'Cab. pesada de arq.'),
('Skirmisher', 'en', 'Skirmisher'),
('Skirmisher', 'es', 'Hostigador'),
('EliteSkirmisher', 'en', 'Elite Skirmisher'),
('EliteSkirmisher', 'es', 'Hostigador de élite'),
('ImperialSkirmisher', 'en', 'Imperial Skirmisher'),
('ImperialSkirmisher', 'es', 'Hostigador imperial'),
('Archer', 'en', 'Archer'),
('Archer', 'es', 'Arquero'),
('Crossbowman', 'en', 'Crossbowman'),
('Crossbowman', 'es', 'Ballestero'),
('Arbalester', 'en', 'Arbalester'),
('Arbalester', 'es', 'Arbalestero'),
('PlumedArcher', 'en', 'Plumed Archer'),
('PlumedArcher', 'es', 'Arquero emplumado'),
('ElitePlumedArcher', 'en', 'Elite Plumed Archer'),
('ElitePlumedArcher', 'es', 'Arquero emplumado'),
('Slinger', 'en', 'Slinger'),
('Slinger', 'es', 'Hondero'),
('Kamayuk', 'en', 'Kamayuk'),
('Kamayuk', 'es', 'Kamayuk'),
('EliteKamayuk', 'en', 'Elite Kamayuk'),
('EliteKamayuk', 'es', 'Kamayuk de élite'),
('Legionary', 'en', 'Legionary'),
('Legionary', 'es', 'Legionario'),
('Centurion', 'en', 'Centurion'),
('Centurion', 'es', 'Centurión'),
('EliteCenturion', 'en', 'Elite Centurion'),
('EliteCenturion', 'es', 'Centurión de élite'),
('Dromon', 'en', 'Dromon'),
('Dromon', 'es', 'Dromón'),
('CompositeBowman', 'en', 'Composite Bowman'),
('CompositeBowman', 'es', 'Arquero con arco compuesto'),
('EliteCompositeBowman', 'en', 'Elite Composite Bowman'),
('EliteCompositeBowman', 'es', 'Arquero con arco compuesto de élite'),
('Monaspa', 'en', 'Monaspa'),
('Monaspa', 'es', 'Monaspa'),
('EliteMonaspa', 'en', 'Elite Monaspa'),
('EliteMonaspa', 'es', 'Monaspa de élite'),
('WarriorPriest', 'en', 'Warrior Priest'),
('WarriorPriest', 'es', 'Sacerdote guerrero')
on conflict DO NOTHING;
