-- Counter coverage pass: 134 edges the catalog was missing, plus a per-edge note.
-- Cross-checked line by line against aoecompanion.com/counters; 15 of their edges were
-- dropped as mechanically unsound (mostly "Samurai beats every unique unit" and
-- "spearmen beat anything mounted", which does not hold for units they cannot catch).

alter table counter
  add column reason_en text,
  add column reason_es text;

insert into counter (line_id, counter_line_id, source) values
('Arambai', 'EagleScout', 'seed'),
('Archer', 'Huskarl', 'seed'),
('Archer', 'RattanArcher', 'seed'),
('Archer', 'WarWagon', 'seed'),
('Archer', 'Genitour', 'seed'),
('Archer', 'MagyarHuszar', 'seed'),
('BallistaElephant', 'FlamingCamel', 'seed'),
('BatteringRam', 'Villager', 'seed'),
('BatteringRam', 'JaguarWarrior', 'seed'),
('BatteringRam', 'Keshik', 'seed'),
('BatteringRam', 'Leitis', 'seed'),
('BatteringRam', 'Huskarl', 'seed'),
('BatteringRam', 'Konnik', 'seed'),
('BatteringRam', 'Kamayuk', 'seed'),
('BatteringRam', 'Samurai', 'seed'),
('BattleElephant', 'Missionary', 'seed'),
('BattleElephant', 'FlamingCamel', 'seed'),
('Berserk', 'Cataphract', 'seed'),
('Berserk', 'Archer', 'seed'),
('Berserk', 'Longbowman', 'seed'),
('Berserk', 'RattanArcher', 'seed'),
('Berserk', 'ChuKoNu', 'seed'),
('BombardCannon', 'Condottiero', 'seed'),
('BombardCannon', 'Mangudai', 'seed'),
('Boyar', 'Samurai', 'seed'),
('CamelRider', 'Kamayuk', 'seed'),
('CamelRider', 'FlamingCamel', 'seed'),
('CamelRider', 'Archer', 'seed'),
('CamelRider', 'Longbowman', 'seed'),
('CamelRider', 'ChuKoNu', 'seed'),
('CamelRider', 'PlumedArcher', 'seed'),
('CamelRider', 'RattanArcher', 'seed'),
('CavalryArcher', 'Genitour', 'seed'),
('CavalryArcher', 'Mameluke', 'seed'),
('Conquistador', 'Knight', 'seed'),
('EagleScout', 'JaguarWarrior', 'seed'),
('ElephantArcher', 'Missionary', 'seed'),
('ElephantArcher', 'FlamingCamel', 'seed'),
('FireGalley', 'Longboat', 'seed'),
('FlamingCamel', 'Missionary', 'seed'),
('FlamingCamel', 'CavalryArcher', 'seed'),
('FlamingCamel', 'PlumedArcher', 'seed'),
('FlamingCamel', 'RattanArcher', 'seed'),
('FlamingCamel', 'ChuKoNu', 'seed'),
('Galley', 'TurtleShip', 'seed'),
('Galley', 'Longboat', 'seed'),
('Genitour', 'Knight', 'seed'),
('GenoeseCrossbowman', 'Samurai', 'seed'),
('HandCannoneer', 'Mangudai', 'seed'),
('HandCannoneer', 'Konnik', 'seed'),
('HandCannoneer', 'Huskarl', 'seed'),
('HandCannoneer', 'Genitour', 'seed'),
('HandCannoneer', 'Longbowman', 'seed'),
('Huskarl', 'JaguarWarrior', 'seed'),
('Janissary', 'Samurai', 'seed'),
('Kamayuk', 'Missionary', 'seed'),
('Kamayuk', 'JaguarWarrior', 'seed'),
('Kamayuk', 'Samurai', 'seed'),
('Kamayuk', 'Gbeto', 'seed'),
('Kamayuk', 'ThrowingAxeman', 'seed'),
('Kipchak', 'CamelArcher', 'seed'),
('Knight', 'Missionary', 'seed'),
('Knight', 'Leitis', 'seed'),
('Knight', 'FlamingCamel', 'seed'),
('Konnik', 'HandCannoneer', 'seed'),
('Konnik', 'Spearman', 'seed'),
('Konnik', 'CamelRider', 'seed'),
('Konnik', 'Archer', 'seed'),
('Konnik', 'Samurai', 'seed'),
('KonnikDismounted', 'HandCannoneer', 'seed'),
('KonnikDismounted', 'Spearman', 'seed'),
('KonnikDismounted', 'CamelRider', 'seed'),
('KonnikDismounted', 'Archer', 'seed'),
('KonnikDismounted', 'Samurai', 'seed'),
('Leitis', 'Archer', 'seed'),
('Legionary', 'Longbowman', 'seed'),
('Legionary', 'PlumedArcher', 'seed'),
('Legionary', 'CamelArcher', 'seed'),
('Legionary', 'Arambai', 'seed'),
('Legionary', 'WarElephant', 'seed'),
('Longbowman', 'Mangonel', 'seed'),
('Longbowman', 'BatteringRam', 'seed'),
('MagyarHuszar', 'Samurai', 'seed'),
('Mangonel', 'Missionary', 'seed'),
('Mangonel', 'Leitis', 'seed'),
('Militia', 'Longbowman', 'seed'),
('Militia', 'PlumedArcher', 'seed'),
('Militia', 'CamelArcher', 'seed'),
('Militia', 'Arambai', 'seed'),
('Militia', 'WarElephant', 'seed'),
('Missionary', 'EagleScout', 'seed'),
('Monk', 'MagyarHuszar', 'seed'),
('Monk', 'Archer', 'seed'),
('Monk', 'PlumedArcher', 'seed'),
('Monk', 'RattanArcher', 'seed'),
('Monk', 'Longbowman', 'seed'),
('Petard', 'Longbowman', 'seed'),
('Petard', 'PlumedArcher', 'seed'),
('PlumedArcher', 'WarWagon', 'seed'),
('PlumedArcher', 'BatteringRam', 'seed'),
('RattanArcher', 'BombardCannon', 'seed'),
('RattanArcher', 'BatteringRam', 'seed'),
('Scorpion', 'Huskarl', 'seed'),
('Scorpion', 'Longbowman', 'seed'),
('Scorpion', 'MagyarHuszar', 'seed'),
('Scorpion', 'Mangudai', 'seed'),
('Scorpion', 'Cataphract', 'seed'),
('ScoutCavalry', 'FlamingCamel', 'seed'),
('ShotelWarrior', 'Samurai', 'seed'),
('ShotelWarrior', 'JaguarWarrior', 'seed'),
('ShotelWarrior', 'Scorpion', 'seed'),
('SiegeTower', 'WoadRaider', 'seed'),
('SiegeTower', 'Mangudai', 'seed'),
('SiegeTower', 'Leitis', 'seed'),
('Skirmisher', 'Condottiero', 'seed'),
('Skirmisher', 'Leitis', 'seed'),
('Skirmisher', 'Keshik', 'seed'),
('Skirmisher', 'WoadRaider', 'seed'),
('Skirmisher', 'ThrowingAxeman', 'seed'),
('Skirmisher', 'Huskarl', 'seed'),
('Skirmisher', 'Samurai', 'seed'),
('Skirmisher', 'Berserk', 'seed'),
('Skirmisher', 'JaguarWarrior', 'seed'),
('Skirmisher', 'Kamayuk', 'seed'),
('Skirmisher', 'ShotelWarrior', 'seed'),
('Skirmisher', 'Gbeto', 'seed'),
('Skirmisher', 'KarambitWarrior', 'seed'),
('Slinger', 'CavalryArcher', 'seed'),
('Spearman', 'Longbowman', 'seed'),
('Spearman', 'PlumedArcher', 'seed'),
('Spearman', 'JaguarWarrior', 'seed'),
('Spearman', 'GenoeseCrossbowman', 'seed'),
('SteppeLancer', 'GenoeseCrossbowman', 'seed'),
('SteppeLancer', 'Gbeto', 'seed'),
('SteppeLancer', 'ThrowingAxeman', 'seed'),
('SteppeLancer', 'Berserk', 'seed'),
('Thirisadai', 'FireGalley', 'seed'),
('Trebuchet', 'Mangudai', 'seed'),
('WarElephant', 'FlamingCamel', 'seed'),
('WarWagon', 'Missionary', 'seed'),
('WarWagon', 'CamelRider', 'seed'),
('WarWagon', 'Berserk', 'seed'),
('WarWagon', 'CamelArcher', 'seed'),
('WoadRaider', 'JaguarWarrior', 'seed')
on conflict (line_id, counter_line_id) do nothing;

-- Per-edge notes. Only the matchups where the raw pairing is misleading without a caveat:
-- the counter needs micro, a specific composition, or only works in one direction.
update counter set reason_en = v.en, reason_es = v.es
from (values
  ('Knight', 'Berserk',
   'Only in numbers and with upgrades: a lone Berserk loses the trade.',
   'Solo en masa y con mejoras: un Berserker suelto pierde el intercambio.'),
  ('Mangonel', 'Mangudai',
   'Their bonus damage against siege lets them delete mangonels before they fire.',
   'Su daño extra contra asedio les permite eliminar mangoneles antes de que disparen.'),
  ('Longbowman', 'Mangonel',
   'Works against a static mass; a spread-out Longbowman ball outranges the mangonel.',
   'Funciona contra una masa estática; si están dispersos, el Arquero largo supera su alcance.'),
  ('Longbowman', 'BatteringRam',
   'The ram absorbs arrows while your own units close the distance.',
   'El ariete absorbe las flechas mientras tus unidades acortan la distancia.'),
  ('Archer', 'BombardCannon',
   'Expensive and slow: only worth it against a large, committed archer mass.',
   'Caro y lento: solo compensa contra una masa grande y comprometida de arqueros.'),
  ('Archer', 'Mangonel',
   'One shot can wipe a clumped group, but archers that spread out will kill it.',
   'Un disparo puede barrer un grupo apiñado, pero si se dispersan lo matan.'),
  ('Archer', 'Huskarl',
   'Their pierce armor makes them nearly immune to archer fire.',
   'Su armadura de perforación los hace casi inmunes al fuego de los arqueros.'),
  ('Archer', 'BatteringRam',
   'Use it as a shield to walk your melee units into the archers.',
   'Úsalo como escudo para meter a tus unidades cuerpo a cuerpo entre los arqueros.'),
  ('Mangudai', 'Spearman',
   'Only if the Mangudai are cornered or attacking; they outrun spearmen in the open.',
   'Solo si están acorralados o atacando; en campo abierto los Mangudai los dejan atrás.'),
  ('Mangudai', 'Skirmisher',
   'Needs numbers: Elite Skirmishers trade well but cannot chase them down.',
   'Requiere masa: los Guerrilleros de élite intercambian bien pero no pueden perseguirlos.'),
  ('Mangudai', 'Huskarl',
   'High pierce armor, but they still have to catch them.',
   'Mucha armadura de perforación, pero aún tienen que alcanzarlos.'),
  ('CavalryArcher', 'Mangonel',
   'Only against a clumped mass; cavalry archers usually kite out of range.',
   'Solo contra una masa apiñada; los arqueros a caballo suelen salirse de su alcance.'),
  ('CavalryArcher', 'Huskarl',
   'They survive the arrows, but need the cavalry archers to be pinned.',
   'Sobreviven a las flechas, pero necesitan que los arqueros a caballo estén acorralados.'),
  ('BallistaElephant', 'Spearman',
   'Cheap and effective, but the elephant''s splash punishes tight formations.',
   'Barato y eficaz, pero el daño en área del elefante castiga las formaciones apretadas.'),
  ('BatteringRam', 'Villager',
   'Villagers do bonus damage to siege: pull them off resources to save a building.',
   'Los aldeanos hacen daño extra al asedio: sácalos de los recursos para salvar un edificio.'),
  ('PlumedArcher', 'Mangonel',
   'Hard to land: Plumed Archers are fast enough to walk out of the shot.',
   'Difícil de acertar: los Arqueros emplumados son rápidos y esquivan el disparo.'),
  ('PlumedArcher', 'BatteringRam',
   'A shield to close the gap, since Plumed Archers kite most melee units.',
   'Un escudo para acortar distancia, ya que los Arqueros emplumados esquivan al cuerpo a cuerpo.'),
  ('Boyar', 'Berserk',
   'Needs a large group: Boyar melee armor blunts most infantry attacks.',
   'Requiere un grupo grande: la armadura del Boyardo amortigua a casi toda la infantería.'),
  ('ChuKoNu', 'Mangonel',
   'Chu Ko Nu clump up to focus fire, which makes them a perfect mangonel target.',
   'Los Chu Ko Nu se agrupan para concentrar el fuego, lo que los hace blanco perfecto del mangonel.'),
  ('ChuKoNu', 'Huskarl',
   'Their pierce armor shrugs off the extra arrows.',
   'Su armadura de perforación ignora las flechas adicionales.'),
  ('RattanArcher', 'Mangonel',
   'Their pierce armor is irrelevant against siege splash.',
   'Su armadura de perforación no sirve contra el daño en área del asedio.'),
  ('RattanArcher', 'Huskarl',
   'Both are pierce-resistant, so this comes down to numbers and upgrades.',
   'Ambos resisten la perforación, así que se decide por número y mejoras.'),
  ('RattanArcher', 'BatteringRam',
   'Rams tank the arrows so your melee units can reach them.',
   'Los arietes aguantan las flechas para que tu cuerpo a cuerpo pueda alcanzarlos.'),
  ('CamelArcher', 'Mangonel',
   'Only against a static mass: Camel Archers are mobile enough to dodge.',
   'Solo contra una masa estática: los Arqueros de camello son lo bastante móviles para esquivar.'),
  ('CamelArcher', 'Huskarl',
   'Immune to most of the damage, but slow to close in.',
   'Inmunes a casi todo el daño, pero lentos para acercarse.'),
  ('HandCannoneer', 'Konnik',
   'The Konnik gets a second life dismounted, which wins the trade.',
   'El Konnik tiene una segunda vida a pie, lo que gana el intercambio.')
) as v(line_id, counter_line_id, en, es)
where counter.line_id = v.line_id and counter.counter_line_id = v.counter_line_id;
